### ISSUE TITLE
provide an (easy) way to execute most of integration tests directory from mfxxx module

### ISSUE THREAD

**Issue by thefab** [metwork-framework/resources#18]

**Comment by thebaptiste** [comment]
I think that what you've done for test 0002_issue21 in mfbase could be generalized and be the way : 
* test*sh are the tests run in mfxxx-integration-tests-runner
* _test*sh are the tests whe can run directly from mfxx module in dev mode
* test*sh basically do "su --command="_test*.sh" - mfxxx"

**Comment by thefab** [comment]
Just to summarize:

- when you are executing tests directly from mfxxx module, you can't use `su --command=... -mfxxx`
- to execute tests directly from mfxxx module, you have to do (only) : `cd integration_tests && make test`
- the remaining question is "can we image a test which can't run like this ?"

I think that we can have some very particular tests (testing `mfext_wrapper` for example) which must be run in root. But it's not the main case. Maybe, we can drop them for the moment.

So my proposal (to discuss) would be:

- we add a `Makefile` (for `make test` usage only) in `mfxxx/integration_tests`
- we add a `run_tests.sh` implementation to execute all executable `test*` files (and not only `test*.sh` files)
- the `Makefile` execute `run_tests.sh` as the current user

For `*runner` repositories:

- we execute the corresponding `make test` as synxxx user

Each integration test must consider that the module is stopped before the execution.Maybe it would be nice if it is enforced in `run_tests.sh` :

- at the beginning, we do a mfxxx.init
- then we loop into tests
- for each test, we do mfxxx.stop then we execute the test

To discuss

**Comment by thefab** [comment]
done
