### ISSUE TITLE
use new LOGPROXY_LOG_DIRECTORY

### ISSUE THREAD

**Issue by thefab** [metwork-framework/resources#54]
- [x] set in the common profile (if `MFMODULE != "MFEXT"`): `export LOGPROXY_LOG_DIRECTORY="${MFMODULE_RUNTIME_HOME}/log"`
- [ ] change all log_proxy usages to remove the absolute log path in:
    - [x] mfext (templates)
    - [x] mfserv (including plugin templates)
    - [x] mfbase (including plugin templates)
    - [x] mfdata (including plugin templates)
    - [x] mfadmin
    - [x] mfsysmon

**Comment by thefab** [comment]
everything is done here, isn't it?

**Comment by thebaptiste** [comment]
Yes, let's close
