### ISSUE TITLE
add php support

### ISSUE THREAD

**Issue by thefab** [metwork-framework/resources#57]

**Comment by thefab** [comment]
- [ ] fastcgi support (fpm)
- [ ] https://getcomposer.org/
- [ ] opcache (opcode cache)

**Comment by thebaptiste** [comment]
php is not available in a dedicated addon (mfextaddon_php).
We now have to use it in mfserv, via a new plugin template.

**Comment by thebaptiste** [comment]
Abandoned, at least for the time being
